trainer:
  max_epochs: 31
  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      resume: allow
      project: "eomt"
      name: "ade20k_semantic_eomt_base_512_augreg"
model:
  class_path: training.mask_classification_semantic.MaskClassificationSemantic
  init_args:
    attn_mask_annealing_enabled: True
    attn_mask_annealing_start_steps: [6520, 16300, 26080]
    attn_mask_annealing_end_steps: [13040, 22820, 32600]
    network:
      class_path: models.eomt.EoMT
      init_args:
        num_q: 100
        num_blocks: 3
        encoder:
          class_path: models.vit.ViT
          init_args:
            backbone_name: vit_base_patch16_384
data:
  class_path: datasets.ade20k_semantic.ADE20KSemantic